# Generated by Django 4.1.3 on 2022-12-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_alter_customer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
