# Generated by Django 4.1.3 on 2022-12-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_alter_customer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
