# Generated by Django 4.1.3 on 2022-12-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_remove_customer_slug_customer_has_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
