# Generated by Django 4.1.3 on 2022-11-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source', models.CharField(choices=[('MARKET', 'Market'), ('FRUIT_VEGETABLES', 'Fruit_Vegetables'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name', 'source'], name='items_item_name_327ee6_idx'),
        ),
    ]
