# Generated by Django 4.1.3 on 2022-11-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_name_327ee6_idx',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='source',
            new_name='category',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name', 'category'], name='items_item_name_1f6d69_idx'),
        ),
    ]
