# Generated by Django 4.1.3 on 2022-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_items_item_name_327ee6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_name_1f6d69_idx',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='items_item_name_1c746e_idx'),
        ),
    ]
