# Generated by Django 4.1.3 on 2022-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
