# Generated by Django 4.1.3 on 2022-12-12 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_alter_customer_mobile"),
        ("orders", "0004_order_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
            ),
        ),
    ]
