# Generated by Django 4.1.3 on 2022-12-23 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0013_alter_customer_name"),
        ("orders", "0007_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
            ),
            preserve_default=False,
        ),
    ]
