# Generated by Django 4.1.3 on 2022-12-24 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_remove_item_items_item_name_1f6d69_idx_and_more"),
        ("orders", "0008_alter_order_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="items.item",
            ),
            preserve_default=False,
        ),
    ]
